// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/supabase';
const SUPABASE_URL = "https://jynukooqgcdeecmjizbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5bnVrb29xZ2NkZWVjbWppemJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDY5MjIsImV4cCI6MjA3MzUyMjkyMn0.iFMJIVxBrkuyLlUsI0no-6hNB6n1FTLuAdXn9fe7Qjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});